# Generated by Django 4.2.4 on 2023-08-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='groups', to='groups.group'),
        ),
    ]
