# Generated by Django 4.2.4 on 2023-08-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
