# Generated by Django 4.2.4 on 2023-08-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_new_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
