# Generated by Django 4.2.4 on 2023-08-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_new_user_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
